### ISSUE TITLE
versioninfo.c missing in master

### ISSUE THREAD

**Issue by cwsheen61** [linz/concord#3]
I just downloaded the zip file for the master branch and attempted to compile.  There was a large number of missing references which I traced back to a missing versioninfo.c file in the /src/concord directory of the download.  I copied the versioninfo.c file from one of the branches and was able to successfully make concord on ubuntu 16.04.  I suggest someone who can validate the full build put a correct copy of versioninfo.c in the correct directory of the master branch

**Comment by ccrook** [comment]
@cwsheen61  - apologies for the very long delay in responding to this.  Somehow it failed to register in my email.  The issue is now fixed - versioninfo.c was not needed by the program but was still required in the makefile.
